export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const FETCH_BRAND_CAT_SUCCESS = 'FETCH_BRAND_CAT_SUCCESS'
export const FETCH_BRAND_CAT_FAIL = 'FETCH_BRAND_CAT_FAIL'

export const POST_ADD_PROD_SUCCESS = 'POST_ADD_PROD_SUCCESS'
export const POST_ADD_PROD_FAIL = 'POST_ADD_PROD_FAIL'

export const FETCH_ADMIN_PROD_SUCCESS = 'FETCH_ADMIN_PROD_SUCCESS'
export const FETCH_ADMIN_PROD_FAIL = 'FETCH_ADMIN_PROD_FAIL'

export const FETCH_EDIT_PROD_SUCCESS = 'FETCH_EDIT_PROD_SUCCESS'
export const FETCH_EDIT_PROD_FAIL = 'FETCH_EDIT_PROD_FAIL'

export const POST_EDIT_PROD_SUCCESS = 'POST_EDIT_PROD_SUCCESS'
export const POST_EDIT_PROD_FAIL = 'POST_EDIT_PROD_FAIL'

export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'




